<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="imdb" nsURI="http://no/ntnu/tdt4250/imdb" nsPrefix="no.ntnu.tdt4250.imdb">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Imdb">
    <eStructuralFeatures xsi:type="ecore:EReference" name="titles" upperBound="-1"
        eType="#//Title" containment="true" eOpposite="#//Title/imdb"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true" eOpposite="#//Person/imdb"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Title">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="startYearConstraint runtimeConstraint uniqueCharactersConstraint imdbNotNullConstraint titleTypeConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="startYearConstraint" value="self.startYear > 0 and self.startYear &lt;= 2050"/>
      <details key="runtimeConstraint" value="self.runtime > 0"/>
      <details key="uniqueCharactersConstraint" value="self.involvements -> isUnique(inv | inv.character)"/>
    </eAnnotations>
    <eOperations name="isFilteredBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="searchString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="caseInsensitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="region" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titleType" lowerBound="1"
        eType="#//TitleType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rating" eType="#//Rating"
        containment="true" eOpposite="#//Rating/title"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvements" upperBound="-1"
        eType="#//Involvement" containment="true" eOpposite="#//Involvement/title"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imdb" eType="#//Imdb" eOpposite="#//Imdb/titles"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TvSeries" eSuperTypes="#//Title">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="endYearConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="endYearConstraint" value="(self.endYear > 0 and self.endYear &lt;= 2050 and self.endYear >= self.startYear) or self.endYear = -1"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="episodes" upperBound="-1"
        eType="#//Episode" containment="true" eOpposite="#//Episode/series"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Episode" eSuperTypes="#//Title">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noImdbContainerConstraint seasonNumberConstraint episodeNumberConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="noImdbContainerConstraint" value="self.imdb = null"/>
      <details key="seasonNumberConstraint" value="self.seasonNumber > 0"/>
      <details key="episodeNumberConstraint" value="self.episodeNumber > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="series" lowerBound="1"
        eType="#//TvSeries" eOpposite="#//TvSeries/episodes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seasonNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="episodeNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rating">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="numberOfVotesConstraint averageRatingConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="numberOfVotesConstraint" value="self.numberOfVotes > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageRating" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfVotes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" lowerBound="1" eType="#//Title"
        eOpposite="#//Title/rating"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="birthYearConstraint deathYearConstraint"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="birthYearConstraint" value="self.birthYear > 0 and self.birthYear &lt;= 2019"/>
      <details key="deathYearConstraint" value="(self.deathYear > 0 and self.deathYear &lt;= 2019 and self.deathYear >= self.birthYear) or self.deathYear = -1"/>
    </eAnnotations>
    <eOperations name="isFilteredBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="searchString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="caseInsensitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthYear" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deathYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="professions" upperBound="3"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knownForTitles" upperBound="-1"
        eType="#//Title"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvement" upperBound="-1"
        eType="#//Involvement" eOpposite="#//Involvement/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imdb" lowerBound="1" eType="#//Imdb"
        eOpposite="#//Imdb/persons"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Involvement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueJobPerPersonConstraint actorIsBornConstraint"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="title" lowerBound="1" eType="#//Title"
        eOpposite="#//Title/involvements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/involvement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="character" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TitleType">
    <eLiterals name="OTHER" value="-1"/>
    <eLiterals name="MOVIE"/>
    <eLiterals name="SHORT" value="1"/>
    <eLiterals name="TVSERIES" value="2"/>
    <eLiterals name="TVEPISODE" value="3"/>
    <eLiterals name="VIDEO" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TitleTypeWrapper">
    <eOperations name="equals" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eOperations name="hashCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titleType" lowerBound="1"
        eType="#//TitleType"/>
  </eClassifiers>
</ecore:EPackage>
